test_end_point: test_end_point
test_api_key: test_api_key
test_team_key: test_team_key
blank_key:
end_point: http://testflightapp.com/api/builds.json
api_key: <YOUR API KEY>
team_key: <YOUR TEAM KEY>
dist_list:
  - <YOUR EMAIL HERE>
